name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nix-flake-check:
    runs-on: codeberg-small

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: https://github.com/cachix/install-nix-action@v31.9.0
        with:
          GITHUB_TOKEN: ""

      - name: Run nix flake check
        run: nix flake check
