name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  nix-flake-check:
    runs-on: codeberg-medium

    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Set up Nix
        uses: https://github.com/cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          GITHUB_TOKEN: ""

      - name: Run nix flake check
        run: nix flake check
