name: Renovate

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  renovate:
    runs-on: codeberg-tiny-lazy

    permissions:
      contents: write
      pull-requests: write

    container:
      image: renovate/renovate:latest@sha256:db781a0898340ca65159a865df1448c471bf093a5fb206fd369a901beb46f8db

    steps:
      - name: Run Renovate
        run: renovate
        env:
          RENOVATE_PLATFORM: forgejo
          RENOVATE_ENDPOINT: https://codeberg.org/api/v1
          RENOVATE_REPOSITORIES: ${{ forgejo.repository }}
          RENOVATE_TOKEN: ${{ secrets.FORGEJO_TOKEN }}

          # Tries to access a nonexistant user "forgejo-actions"
          RENOVATE_IGNORE_PR_AUTHOR: true

          # Disable throughput limit
          RENOVATE_PR_HOURLY_LIMIT: 0

          # If things go wrong I want to know why
          LOG_LEVEL: debug

          # Needed for github data source
          GITHUB_COM_TOKEN: ${{ secrets.GH_COM_TOKEN }}
